I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script
    $ renpy.pause()
  File "game/script.rpy", line 16, in <module>
    $ renpy.pause()
  File "game/screens.rpy", line 115, in execute
    screen expr:
  File "game/screens.rpy", line 115, in execute
    screen expr:
  File "game/screens.rpy", line 117, in execute
    frame xmaximum 200:
  File "game/screens.rpy", line 119, in execute
    has vbox
  File "game/screens.rpy", line 122, in execute
    bar value mi range 16
  File "game/screens.rpy", line 122, in keywords
    bar value mi range 16
  File "game/screens.rpy", line 122, in <module>
    bar value mi range 16
NameError: name 'mi' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script
    $ renpy.pause()
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 16, in <module>
    $ renpy.pause()
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\exports.py", line 1537, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 3810, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\screen.py", line 451, in visit_all
    callback(self)
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\core.py", line 3810, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\screen.py", line 462, in per_interact
    self.update()
  File "C:\Users\dirty\Desktop\renpy-8.0.3-sdk\renpy\display\screen.py", line 653, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 115, in execute
    screen expr:
  File "game/screens.rpy", line 115, in execute
    screen expr:
  File "game/screens.rpy", line 117, in execute
    frame xmaximum 200:
  File "game/screens.rpy", line 119, in execute
    has vbox
  File "game/screens.rpy", line 122, in execute
    bar value mi range 16
  File "game/screens.rpy", line 122, in keywords
    bar value mi range 16
  File "game/screens.rpy", line 122, in <module>
    bar value mi range 16
NameError: name 'mi' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Chalice of Lendon 1.0
Thu Feb 23 19:50:52 2023
